apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-http-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-http-demo
  template:
    metadata:
      labels:
        app: simple-http-demo
    spec:
      containers:
      - name: simple-http-demo
        image: xihashking/simple-http-demo:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: simple-http-service
spec:
  type: NodePort
  selector:
    app: simple-http-demo
  ports:
  - port: 8000
    targetPort: 8000 